### ISSUE TITLE
Run SiLA 2 server on integrated Raspi

### ISSUE THREAD

**Issue by NMertsch** [FlorianBauer/ot2-controller#2]
Regarding your idea of running the SiLA 2 server directly on the Raspberry Pi integrated in the OT-2: Couldn't you just `git clone` or `scp` the reqired code to the Raspi, `pip install` everything and start the server there via `ssh`?

**Comment by FlorianBauer** [comment]
Indeed, in theory you can "just" do this. You probably could even configure the system to automatically start up the SiLA service when the device gets turned on. But in practice it is a bit more complicated (of course).

One thing is, that it can not be granted that a firmware/software update of the OT-2 not overwrites the installed settings. The only place where things can be put safely on the device is the `/root/data/user_storage/` directory, everything else may not "survive" an update (including environment variables etc.). 

It should also be mentioned, that the behavior of a standalone protocol executed directly on the device divers from the usage within the App. This is currently the case and must be kept in mind by the users. For example, the App ensures the device is always calibrated before running a protocol and implicitly delivers the adjustments in the context of the executed script. On standalone usage, this data has to be explicitly provided in the protocol itself. Same goes for custom Labware definitions and maybe some other things I am not aware of. So a user has to be aware of those differences, otherwise a protocol may run flawlessly in the App but not within this SiLA service.

However, if someone is brave enough to try a direct install on the device, I would be very interested to see a guide with the configuration steps to do so.

**Comment by NMertsch** [comment]
Sadly my department gave away the OT-2, so I cannot test that. And I totally understand that you don't want to test an idea of some random person on the internet on your device.

Regarding system updates: Opentrons provides the SD card image of the software and instructions for resetting everything, so in the worst case you can always restore to factory settings. [url](https://support.opentrons.com/en/articles/5568992-reflashing-the-ot-2-s-sd-card)

Regarding the system behaving differently when running via SiLA or the Opentrons App: That problem is independent from where the server is hosted, right?

Regarding installation: If this repo contains an installable Python package (e.g. with a setup.py), you can install it like this (via ssh):
```shell
wget https://github.com/FlorianBauer/ot2-controller/archive/refs/heads/master.zip
pip install master.zip
```

And to automatically start the server, you can use one of the many ways Linux provides, e.g. a systemd service.

But I'm not sure if that's a better solution than your current ssh-based approach. Feel free to close this issue btw, I just opened it to exchange ideas.

**Comment by FlorianBauer** [comment]
> Sadly my department gave away the OT-2, so I cannot test that.

I have (kind of) the same problem, so I hoped someone could try it.

> Regarding system updates: Opentrons provides the SD card image of the software and instructions for  resetting everything, so in the worst case you can always restore to factory settings. [url](https://support.opentrons.com/en/articles/5568992-reflashing-the-ot-2-s-sd-card)

This is true and usually not a problem for developers. However, the lab staff operating the device is usually not aware of that and may accidentally make a update while using the OT-2 App.

> But I'm not sure if that's a better solution than your current ssh-based approach.

The idea has definitely its appeal, otherwise I would not have mentioned it in the README. But I decided to use the SSH-based approach since users often adjust and extend their protocols before using them. After that, they have to get the modified version to the device, which requires a SSH connection anyway.

> Feel free to close this issue btw, I just opened it to exchange ideas.

Its fine. This is basically my fault since I had forgotten to enable discussion in the repository settings.
